# Generated by Django 4.0.2 on 2022-02-02 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('documento', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=14)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=11)),
                ('especie', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=30)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.propietario')),
            ],
        ),
    ]
