# Generated by Django 4.0.2 on 2022-02-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_rename_documento_mascota_propietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('documento', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=14)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
