# Generated by Django 4.0.2 on 2022-02-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0007_factura_detallefactura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroclinico',
            old_name='id_mascota',
            new_name='mascota',
        ),
        migrations.RenameField(
            model_name='registroclinico',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='registroclinico',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
