# Generated by Django 4.0.2 on 2022-02-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0008_rename_id_mascota_registroclinico_mascota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefactura',
            old_name='id_factura',
            new_name='factura',
        ),
        migrations.RenameField(
            model_name='detallefactura',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='id_propietario',
            new_name='propietario',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
